---
# tasks file for mapr-rh-prereqs
- name: save the current list of installed packages
  shell: rpm -qa --queryformat '%{NAME}\t%{VERSION}\n' > packages_before_prereqs
  args:
    creates: packages_before_prereqs

- name: configure proxy for yum
  become: yes
  become_user: root
  lineinfile: dest=/etc/yum.conf line=proxy={{proxy_env.http_proxy}} regexp=^proxy backup=yes
  when: proxy_env.http_proxy is defined

- name: test external url
  get_url: url=http://example.com dest=/dev/null 
  environment: '{{proxy_env}}'

- name: install libselinux-python tools
  yum: name="{{item}}" state=present
  become: yes
  become_user: root
  environment: '{{proxy_env}}'
  with_items:
    - libselinux-python

- name: install sdparm
  yum: name=http://centos.aol.com/6/os/x86_64/Packages/sdparm-1.04-1.1.el6.x86_64.rpm state=present
  become: yes
  become_user: root
  environment: '{{proxy_env}}'
  when: ansible_distribution == 'Amazon'

- name: set selinux config to permissive
  selinux: state=permissive policy=targeted
  become: yes
  become_user: root
  when: ansible_distribution not in ('Amazon')

- name: selinux to permissive now
  command: setenforce permissive
  become: yes
  become_user: root
  when: ansible_distribution not in ('Amazon')

- name: disable iptables
  service: name=iptables state=stopped enabled=no
  become: yes
  become_user: root
  when: ansible_distribution_major_version < "7"

- name: write /etc/hosts with cluster node names
  become: yes
  become_user: root
  template: src=hosts.j2 dest=/etc/hosts mode=0644 

- name: install repo for RedHat-based Linux
  become: yes
  become_user: root
  template: src=maprtech.repo.j2 dest=/etc/yum.repos.d/maprtech.repo mode=0644 owner=root group=root

- name: install Java 1.7
  yum: name={{item}} state=present
  become: yes
  become_user: root
  environment: '{{proxy_env}}'
  with_items:
    - java-1.7.0-openjdk
    - java-1.7.0-openjdk-devel

- name: install nfs-utils to get rpcbind
  environment: '{{proxy_env}}'
  yum: name=nfs-utils state=installed
  become: yes
  become_user: root

- name: ensure NFS server is disabled
  service: name=nfs state=stopped enabled=no
  become: yes
  become_user: root

- name: ensure rpcbind starts
  service: name=rpcbind state=started enabled=yes
  become: yes
  become_user: root

- name: ensure TCP retries are set to 5
  lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.tcp_retries2" line="net.ipv4.tcp_retries2=5"
  become: yes
  become_user: root
  notify: reload sysctl

- name: disable memory overcommit
  lineinfile: dest=/etc/sysctl.conf regexp="^vm.overcommit_memory" line="vm.overcommit_memory=0"
  become: yes
  become_user: root
  notify: reload sysctl

- name: install the MapR GPG key
  tags:
    - external
  rpm_key: state=present key=http://{{mirror_host}}/releases/pub/maprgpg.key
  become: yes
  become_user: root
  environment: '{{proxy_env}}'
  when: gpgcheck == 1

- name: save the current list of installed packages after prereqs
  shell: rpm -qa --queryformat '%{NAME}\t%{VERSION}\n' > packages_after_prereqs
  args:
    creates: /root/packages_after_prereqs
