---
# handlers file for mapr-rh-prereqs

- name: restart ntp
  become: yes
  become_user: root
  service: name=ntpd state=restarted

- name: reload sysctl
  become: yes
  become_user: root
  command: sysctl -e -p
